spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /.well-known/**, /users/**


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/fcm-tokens/**, /notifications/**

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
