apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Namespace }}
data:
  EUREKA_SERVER: {{ .Values.secrets.eurekaServer }}
  CLIENT_ID: {{ .Values.secrets.clientId }}
  CLIENT_SECRET: {{ .Values.secrets.clientSecret }}
  JWT_DURATION: {{ .Values.secrets.jwtDuration }}
  PRIVATE_KEY_KID: {{ .Values.secrets.privateKeyKid }}
  PUBLIC_KEY: {{ .Values.secrets.publicKey }}
  PRIVATE_KEY: {{ .Values.secrets.privateKey }}
  CORS_ORIGINS: {{ .Values.secrets.corsOrigins }}
  AWS_KEY: {{ .Values.secrets.awsKey }}
  AWS_SECRET: {{ .Values.secrets.awsSecret }}
  AWS_BUCKET_NAME: {{ .Values.secrets.awsBucketName }}
  AWS_BUCKET_REGION: {{ .Values.secrets.awsBucketRegion }}
  KAFKA_SASL_USERNAME: {{ .Values.secrets.kafkaSaslUsername }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.kafkaSaslPassword }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret }}
  DB_HOST: {{ .Values.secrets.dbHost }}
  DB_PORT: {{ .Values.secrets.dbPort }}
  DB_NAME: {{ .Values.secrets.dbName }}
  DB_USERNAME: {{ .Values.secrets.dbUsername }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}