name: Push Images to Docker and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Maven Project
        run: mvn -B package --file pom.xml

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Tests
        run: mvn test --file pom.xml

  sonar_analyze:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          jdk-version: '17'
          distribution: 'zulu'

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=244walyson_GWApp


  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: sonar_analyze
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check for changed files
        id: check_changes
        run: |
          git fetch
          echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Set Tag
        id: get_tag
        run: echo "DOCKER_TAG=$(echo ${{ github.run_number }} | cut -c1-6)" >> $GITHUB_ENV

      - name: Build and Push Gateway Services
        if: steps.check_changes.outputs.changed == 'gateway-service/*'
        run: |
          cd gateway-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-service:${{ env.DOCKER_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:${{ env.DOCKER_TAG }}

      - name: Build and Push Discovery Services
        if: steps.check_changes.outputs.changed == 'discovery-service/*'
        run: |
          cd discovery-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery-service:${{ env.DOCKER_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/discovery-service:${{ env.DOCKER_TAG }}

      - name: Build and Push Auth Services
        if: steps.check_changes.outputs.changed == 'auth-service/*'
        run: |
          cd auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ env.DOCKER_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ env.DOCKER_TAG }}

      - name: Build and Push Chat Services
        if: steps.check_changes.outputs.changed == 'chat-service/*'
        run: |
          cd chat-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-service:${{ env.DOCKER_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-service:${{ env.DOCKER_TAG }}

      - name: Build and Push Notification Services
        if: steps.check_changes.outputs.changed == 'notification-service/*'
        run: |
          cd notification-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:${{ env.DOCKER_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:${{ env.DOCKER_TAG }}
