name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_gateway_service:
    name: Build Gateway Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Maven Project
        run: mvn -B package --file gateway-service/pom.xml

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Docker Image
        run: |
          cd gateway-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-service:${{ github.run_number }} .
      - name: Save Docker Image to Tarball
        run: docker save ${{ secrets.DOCKER_USERNAME }}/gateway-service:${{ github.run_number }} -o gateway-service.tar

      - name: Upload Docker Image Tarball
        uses: actions/upload-artifact@v3
        with:
          name: gateway-service-image
          path: gateway-service.tar

  build_discovery_service:
    name: Build Discovery Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Maven Project
        run: mvn -B package --file discovery-service/pom.xml

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Docker Image
        run: |
          cd discovery-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery-service:${{ github.run_number }} .
      - name: Save Docker Image to Tarball
        run: docker save ${{ secrets.DOCKER_USERNAME }}/discovery-service:${{ github.run_number }} -o discovery-service.tar

      - name: Upload Docker Image Tarball
        uses: actions/upload-artifact@v3
        with:
          name: discovery-service-image
          path: discovery-service.tar

  # Add similar jobs for other services: auth-service, chat-service, notification-service

  analyze_sonar:
    name: SonarCloud Analysis
    needs: [build_gateway_service, build_discovery_service] # Add other services here
    uses: ./.github/workflows/sonar.yml

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: analyze_sonar
    strategy:
      matrix:
        service: [gateway-service, discovery-service, auth-service, chat-service, notification-service]
    steps:
      - name: Download Docker Image Tarball
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.service }}-image
          path: ${{ matrix.service }}.tar

      - name: Load Docker Image from Tarball
        run: docker load -i ${{ matrix.service }}.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.run_number }}
