name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway-service, discovery-service, auth-service, chat-service, notification-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Maven Project
        run: |
          cd ${{ matrix.service }}
          mvn -B package --file pom.xml

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        id: docker_build
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.run_number }} .

      - name: Save Docker Image to Tarball
        run: docker save ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.run_number }} -o ${{ matrix.service }}.tar

      - name: Upload Docker Image Tarball
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}-image
          path: ${{ matrix.service }}.tar

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Tests
        run: mvn test --file pom.xml

  sonar_analyze:
    name: SonarCloud Analysis
    needs: tests
    uses: ./.github/workflows/sonar.yml


  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: sonar_analyze
    strategy:
      matrix:
        service: [gateway-service, discovery-service, auth-service, chat-service, notification-service]
    steps:
      - name: Download Docker Image Tarball
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.service }}-image
          path: ${{ matrix.service }}.tar

      - name: Load Docker Image from Tarball
        run: docker load -i ${{ matrix.service }}.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.run_number }}
