name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: gateway-service
            projectKey: 244walyson_GWApp_gateway-service
            token: SONAR_TOKEN_GATEWAY_SERVICE
          - name: discovery-service
            projectKey: 244walyson_GWApp_discovery-service
            token: SONAR_TOKEN_DISCOVERY_SERVICE
          - name: auth-service
            projectKey: 244walyson_GWApp_auth-service
            token: SONAR_TOKEN_AUTH_SERVICE
          - name: chat-service
            projectKey: 244walyson_GWApp_chat-service
            token: SONAR_TOKEN_CHAT_SERVICE
          - name: notification-service
            projectKey: 244walyson_GWApp_notification-service
            token: SONAR_TOKEN_NOTIFICATION_SERVICE

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: |
          cd ${{ matrix.service.name }}
          mvn compile

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets[ matrix.service.token ] }}
        run: |
          cd ${{ matrix.service.name }}
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=244walyson \
              -Dsonar.projectKey=${{ matrix.service.projectKey }} \
              -Dsonar.token=${{ env.SONAR_TOKEN }}
